# Publish Docker image
# 1. DOCKER_IMAGE: the name of the docker hub project
# 2. Set the secrets DOCKERHUB_USERNAME
# 3. Set the secrets DOCKERHUB_TOKEN
# 4. Set the secrets ACTIONS_STEP_DEBUG value to true, if you need to debug
name: Publish Docker image
on:
  push:
    tags:
      - '**'
      - '!**-alpha'
jobs:
  build:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
      -
        # tags: name/app:v0.0.1,name/app:latest
        name: Set up env
        id: set_env
        run: |
          DOCKER_IMAGE=azhi/v2fly-core-test
          VERSION=edge
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          fi
          if [ "${{ github.event_name }}" = "schedule" ]; then
            VERSION=nightly
          fi
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          if [[ $VERSION =~ ^.?[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            TAGS="$TAGS,${DOCKER_IMAGE}:latest"
          fi
          echo "Tags is ${TAGS}"
          echo ::set-output name=tags::${TAGS}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: ${{ steps.set_env.outputs.tags }}
