name: Test

on:
  push:
    branches:
      - master
      - v*
    paths:
      - ".github/workflows/*.yml"
      - "**/*.go"
      - "go.mod"
      - "go.sum"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/workflows/*.yml"
      - "**/*.go"
      - "go.mod"
      - "go.sum"

jobs:
  test:
    if: github.repository != 'v2ray/v2ray-core'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-11.0]
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Test
        run: go test -timeout 1h -v ./...
